### ISSUE TITLE
image not showing in production

### ISSUE THREAD

**Issue by Karyum** [FACN8/Learnow#25]
i went in the Netlify for the website and i didn't see the landing page image that you guys added in the project.
https://learnow.netlify.com/

![Screenshot from 2020-03-11 11-35-46](https://user-images.githubusercontent.com/24195641/76402751-81a70780-638c-11ea-9888-8592567dcbfb.png)

**Comment by LogicX1** [comment]
Fixed by changing opacity of the bg-image div from 65% to 0.65
