### ISSUE TITLE
Signing in/up does not always open on netlify

### ISSUE THREAD

**Issue by LogicX1** [FACN8/Learnow#52]

**Comment by LogicX1** [comment]
More details on what just happened:
If you enter the website for the first time, and simply log in then log out or whatever it works.
But opening the site after you were already there at sometime will show this error when u click log in 
![Screenshot from 2020-03-17 12-02-01](https://user-images.githubusercontent.com/57117321/76845397-7c8fff80-6847-11ea-8b7a-580c5e9c5b8d.png)

I used the site yesterday, and today i see a Login (shows only if u are not authenticated) clicking it gives that error in console, then clearing the site data and cache and refreshing , you click log in and you immediately get authenticated without entering anything

**Comment by Karyum** [comment]
isn't this the method (`loginWithRedirect`) from the Auth0 package ?

**Comment by LogicX1** [comment]
yes , it usually works fine except for some cases and only on netlify, i never had this happen when running locally (not yet !)

**Comment by LogicX1** [comment]
Removing the slash at the end from learnow.netlify.com/ at allowed origins in the auth0 config fixed this
